site_name: Guidelines for GACS
theme: 'readthedocs'
repo_url: https://github.com/agrisemantics/gacs-qip
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'Guidelines for GACS'
pages:
- About GACS: gacs.md
- About these guidelines: index.md
- Scope: scope.md
- Labels: labels.md
- Scientific and Common Names: names.md
- Relations between Concepts: relations.md
- Semantic Types: semantic_types.md
- GACS Thematic Classification: thematic_classification.md
- Definitions: definitions.md
- Documentation Properties: docproperties.md
