site_name: Guidelines for GACS
theme: 'readthedocs'
repo_url: https://github.com/agrisemantics/gacs-qip
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'Guidelines for GACS'
pages:
- About these guidelines: index.md
- Global Agricultural Concept Scheme: gacs.md
- Concepts: concepts.md
- Concept relations: relations.md
- Concept definitions: definitions.md
- Concept labels: labels.md
- Scientific and common names: names.md
- Thematic classification: thematic_classification.md
- Scope notes: docproperties.md
