site_name: Guidelines for GACS
theme: 'readthedocs'
repo_url: https://github.com/agrisemantics/gacs-qip
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'Guidelines for GACS'
pages:
- Purpose of GACS: index.md
- Scope: scope.md
- Labels: labels.md
- Scientific and Common Names: names.md
- Relations between Concepts: relations.md
- Semantic Types: semantic_types.md
- Thematic Groups: thematic_groups.md
- Definitions: definitions.md
- Documentation Properties: docproperties.md
- Glossary: glossary.md
- Sources Consulted: sources.md
