PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {
    ?gacsc skos:closeMatch ?item
}
WHERE
{
    ?item wdt:P4427 ?gacsid .
    BIND(IRI(CONCAT('http://id.agrisemantics.org/gacs/C', ?gacsid)) AS ?gacsc)
}
